services:
  web:
    container_name: novi-app
    restart: always
    depends_on: [ postgres ]
    build: novi-app/.
    volumes:
      - ./plugin-activations:/var/plugin-activations
    ports:
      - "8080:8080"
    environment:
      - "spring.datasource.url=jdbc:postgresql://postgres:5432/novi-db"
      - "spring.datasource.username=novi-user"
      - "spring.datasource.password=secret"
      - "activations.plugin.dir=/var/plugin-activations"
  postgres:
    image: "postgres:15.5"
    container_name: "novi-postgres"
    restart: always
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=novi-user'
      - 'POSTGRES_DB=novi-db'
      - 'POSTGRES_PASSWORD=secret'